--------------------------------------------------------
--  파일이 생성됨 - 목요일-11월-30-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence BOOKING_DETAILS_SQ
--------------------------------------------------------

   CREATE SEQUENCE  "GOING"."BOOKING_DETAILS_SQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BOOKING_SQ
--------------------------------------------------------

   CREATE SEQUENCE  "GOING"."BOOKING_SQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence HISTORY_SQ
--------------------------------------------------------

   CREATE SEQUENCE  "GOING"."HISTORY_SQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MEMBER_SQ
--------------------------------------------------------

   CREATE SEQUENCE  "GOING"."MEMBER_SQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PAYMENT_SQ
--------------------------------------------------------

   CREATE SEQUENCE  "GOING"."PAYMENT_SQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence REVIEW_SQ
--------------------------------------------------------

   CREATE SEQUENCE  "GOING"."REVIEW_SQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TRAVEL_AGENCY_SQ
--------------------------------------------------------

   CREATE SEQUENCE  "GOING"."TRAVEL_AGENCY_SQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TRAVEL_ITEM_SQ
--------------------------------------------------------

   CREATE SEQUENCE  "GOING"."TRAVEL_ITEM_SQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table BOOKING
--------------------------------------------------------

  CREATE TABLE "GOING"."BOOKING" 
   (	"BOOKING_ID" NUMBER, 
	"MEMBER_ID" NUMBER, 
	"ITEM_ID" NUMBER, 
	"BOOKING_DATE" DATE DEFAULT sysdate, 
	"HEAD_COUNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LIKED_ITEM
--------------------------------------------------------

  CREATE TABLE "GOING"."LIKED_ITEM" 
   (	"LIKED_ID" NUMBER, 
	"ITEM_ID" NUMBER, 
	"MEMBER_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "GOING"."MEMBER" 
   (	"MEMBER_ID" NUMBER, 
	"EMAIL" VARCHAR2(100 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE), 
	"ROLE" VARCHAR2(20 BYTE), 
	"JOINDATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PAYMENT_TRANSACTION
--------------------------------------------------------

  CREATE TABLE "GOING"."PAYMENT_TRANSACTION" 
   (	"MEMBER_ID" NUMBER, 
	"BOOKING_ID" NUMBER, 
	"TRANSACTION_DATE" DATE, 
	"TOTAL_PRICE" NUMBER, 
	"TRANSACTION_STATUS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REVIEW
--------------------------------------------------------

  CREATE TABLE "GOING"."REVIEW" 
   (	"REVIEW_ID" NUMBER, 
	"MEMBER_ID" NUMBER, 
	"AGENCY_ID" NUMBER, 
	"RATING" NUMBER, 
	"COMMNET" VARCHAR2(500 BYTE), 
	"REVIEW_DATE" DATE DEFAULT sysdate, 
	"REPORTED" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STATUS_HISTORY
--------------------------------------------------------

  CREATE TABLE "GOING"."STATUS_HISTORY" 
   (	"HISTORY_ID" NUMBER, 
	"AGENCY_ID" NUMBER, 
	"STATUS" VARCHAR2(20 BYTE), 
	"STATUS_CHANGE_DATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TRAVEL_AGENCY
--------------------------------------------------------

  CREATE TABLE "GOING"."TRAVEL_AGENCY" 
   (	"AGENCY_ID" NUMBER, 
	"EMAIL" VARCHAR2(100 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"AVERAGE_RATING" NUMBER, 
	"TOTAL_REVIEWS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TRAVEL_ITEM
--------------------------------------------------------

  CREATE TABLE "GOING"."TRAVEL_ITEM" 
   (	"ITEM_ID" NUMBER, 
	"AGENCY_ID" NUMBER, 
	"ITEM_NAME" VARCHAR2(100 BYTE), 
	"AGENCY_NAME" VARCHAR2(100 BYTE), 
	"LOCATION" VARCHAR2(100 BYTE), 
	"PRICE" NUMBER, 
	"DESCRIPTION" VARCHAR2(1000 BYTE), 
	"DEPARTURE_DATE" DATE, 
	"ARRIVAL_DATE" DATE, 
	"LIKE_COUNT" NUMBER DEFAULT 0, 
	"DELETE_YN" CHAR(1 BYTE) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into GOING.BOOKING
SET DEFINE OFF;
REM INSERTING into GOING.LIKED_ITEM
SET DEFINE OFF;
REM INSERTING into GOING.MEMBER
SET DEFINE OFF;
REM INSERTING into GOING.PAYMENT_TRANSACTION
SET DEFINE OFF;
REM INSERTING into GOING.REVIEW
SET DEFINE OFF;
REM INSERTING into GOING.STATUS_HISTORY
SET DEFINE OFF;
REM INSERTING into GOING.TRAVEL_AGENCY
SET DEFINE OFF;
REM INSERTING into GOING.TRAVEL_ITEM
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index REVIEW_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GOING"."REVIEW_PK" ON "GOING"."REVIEW" ("REVIEW_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007225
--------------------------------------------------------

  CREATE UNIQUE INDEX "GOING"."SYS_C007225" ON "GOING"."BOOKING" ("BOOKING_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index LIKED_ITEM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GOING"."LIKED_ITEM_PK" ON "GOING"."LIKED_ITEM" ("LIKED_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "GOING"."MEMBER" ADD UNIQUE (user_NAME)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GOING"."MEMBER" ADD PRIMARY KEY ("MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRAVEL_AGENCY
--------------------------------------------------------

  ALTER TABLE "GOING"."TRAVEL_AGENCY" ADD PRIMARY KEY ("AGENCY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LIKED_ITEM
--------------------------------------------------------

  ALTER TABLE "GOING"."LIKED_ITEM" ADD CONSTRAINT "LIKED_ITEM_PK" PRIMARY KEY ("LIKED_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GOING"."LIKED_ITEM" MODIFY ("LIKED_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STATUS_HISTORY
--------------------------------------------------------

  ALTER TABLE "GOING"."STATUS_HISTORY" ADD PRIMARY KEY ("HISTORY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PAYMENT_TRANSACTION
--------------------------------------------------------

  ALTER TABLE "GOING"."PAYMENT_TRANSACTION" ADD PRIMARY KEY ("MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REVIEW
--------------------------------------------------------

  ALTER TABLE "GOING"."REVIEW" ADD CONSTRAINT "REVIEW_PK" PRIMARY KEY ("REVIEW_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GOING"."REVIEW" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "GOING"."REVIEW" MODIFY ("COMMNET" NOT NULL ENABLE);
  ALTER TABLE "GOING"."REVIEW" MODIFY ("RATING" NOT NULL ENABLE);
  ALTER TABLE "GOING"."REVIEW" MODIFY ("REVIEW_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOOKING
--------------------------------------------------------

  ALTER TABLE "GOING"."BOOKING" ADD CONSTRAINT "SYS_C007225" PRIMARY KEY ("BOOKING_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GOING"."BOOKING" MODIFY ("BOOKING_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRAVEL_ITEM
--------------------------------------------------------

  ALTER TABLE "GOING"."TRAVEL_ITEM" ADD PRIMARY KEY ("ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GOING"."TRAVEL_ITEM" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "GOING"."TRAVEL_ITEM" MODIFY ("AGENCY_NAME" NOT NULL ENABLE);
  ALTER TABLE "GOING"."TRAVEL_ITEM" MODIFY ("ITEM_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BOOKING
--------------------------------------------------------

  ALTER TABLE "GOING"."BOOKING" ADD CONSTRAINT "SYS_C007226" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "GOING"."MEMBER" ("MEMBER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LIKED_ITEM
--------------------------------------------------------

  ALTER TABLE "GOING"."LIKED_ITEM" ADD CONSTRAINT "LIKED_ITEM_FK1" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "GOING"."MEMBER" ("MEMBER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REVIEW
--------------------------------------------------------

  ALTER TABLE "GOING"."REVIEW" ADD CONSTRAINT "REVIEW_FK1" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "GOING"."MEMBER" ("MEMBER_ID") ENABLE;
  ALTER TABLE "GOING"."REVIEW" ADD CONSTRAINT "REVIEW_FK2" FOREIGN KEY ("AGENCY_ID")
	  REFERENCES "GOING"."TRAVEL_AGENCY" ("AGENCY_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STATUS_HISTORY
--------------------------------------------------------

  ALTER TABLE "GOING"."STATUS_HISTORY" ADD FOREIGN KEY ("AGENCY_ID")
	  REFERENCES "GOING"."TRAVEL_AGENCY" ("AGENCY_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRAVEL_ITEM
--------------------------------------------------------

  ALTER TABLE "GOING"."TRAVEL_ITEM" ADD FOREIGN KEY ("AGENCY_ID")
	  REFERENCES "GOING"."TRAVEL_AGENCY" ("AGENCY_ID") ENABLE;
